[package]
name = "syset"
version = "0.1.0"
edition = "2021"
authors = ["Craftwork4498 <craftwork4498@gmail.com>"]
repository = "https://github.com/craftwork4498/syset"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
